#pragma config(Motor,  port2,           motorfl,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motorfr,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           motorbl,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           motorbr,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SET_MOTOR(vfl, vfr, vbl, vbr) \
motor[motorfl] = ((vfl) / REDUCE); \
motor[motorfr] = (-(vfr) / REDUCE); \
motor[motorbl] = ((vbl) / REDUCE); \
motor[motorbr] = (-(vbr) / REDUCE);


const int REDUCE = 1;
const bool LEFT = true; // Enables left-handed ness

int vdelta, hdelta;

task main(){
	for(;;){
		vdelta = LEFT ? vexRT[Ch3] : vexRT[Ch2];
		hdelta = LEFT ? vexRT[Ch4] : vexRT[Ch1];

		SET_MOTOR(vdelta + hdelta, vdelta - hdelta, vdelta + hdelta, vdelta - hdelta);
	}
}
