#pragma config(Motor,  port2,           motorfl,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motorfr,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           motorbl,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           motorbr,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SET_MOTOR(vfl, vfr, vbl, vbr) \
motor[motorfl] = ((vfl) / REDUCE); \
motor[motorfr] = ((vfr) / REDUCE); \
motor[motorbl] = (-(vbl) / REDUCE); \
motor[motorbr] = (-(vbr) / REDUCE)


const int REDUCE = 1;
const bool LEFT = true; // Enables left-handed ness

int up, down, left, right;

task main(){
	for(;;){
		up = LEFT ? vexRT[Btn7U] : vexRT[Btn8U];
		down = LEFT ? vexRT[Btn7D] : vexRT[Btn8D];
		left = LEFT ? vexRT[Btn7L] : vexRT[Btn8L];
		right = LEFT ? vexRT[Btn7R] : vexRT[Btn8R];

		if(up){
			SET_MOTOR(127, 127, 127, 127);
		}
		else if(down){
			SET_MOTOR(-127, -127, -127, -127);
		}
		else if(left){
			SET_MOTOR(-127, 127, -127, 127);
		}
		else if(right){
			SET_MOTOR(127, -127, 127, -127);
		}
		else{
			SET_MOTOR(0, 0, 0, 0);
		}
	}
}
