#pragma config(Sensor, dgtl1,  btnlhs,         sensorDigitalIn)
#pragma config(Sensor, dgtl2,  btnrhs,         sensorDigitalIn)
#pragma config(Motor,  port2,           motor2p,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motor3p,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           motor4p,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           motor5p,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SET_MOTOR(vfl, vfr, vbl, vbr) \
motor[motor2p] = ((vfl) / REDUCE); \
motor[motor3p] = ((vfr) / REDUCE); \
motor[motor4p] = (-(vbl) / REDUCE); \
motor[motor5p] = (-(vbr) / REDUCE)

const int INF = (1 << 30) - 1 + (1 << 30), MV = 127, REDUCE = 1;
int lhs, rhs;

task main(){
	for(;;){
		lhs = !SensorValue[btnlhs];
		rhs = !SensorValue[btnrhs];

		if(lhs){
			SET_MOTOR(MV, MV, MV, MV);
		}
		else if(rhs){
			SET_MOTOR(0, 0, 0, 0);
		}
	}
}
